### ISSUE TITLE
Second starts when call connects but it should when call is received

### ISSUE THREAD

**Issue by hbrawnak** [twilio/voice-quickstart-server-php#7]
When call connects or ringing twilio shows second. Even when ends the call after receiving twilio sends duration in callback from when call connects. But it should when call is received.

**Comment by bobiechen-twilio** [comment]
Hi @hbrawnak 

For app to only receive the "connected" callback when the call has been answered by the callee, please use [the answerOnBridge flag](https://www.twilio.com/docs/voice/twiml/dial#answeronbridge) in your <Dial> verb.

Please note that this only applies when there is no <Say> or <Stream> verb before <Dial> in the TwiML response, otherwise the client will receive the "connected" callback once the connection is established between the caller and Twilio.

Hope this helps.
-bobie

**Comment by hbrawnak** [comment]
Thank you
